title: This is about page
gallery: [test1.jpg,test2.jpg,test3.jpg,test4.jpg,test5.jpg]
contacts:
  -
    ico: vkontakte.png
    href: http://vkontakte.ru/alamix
  -
    ico: facebook.png
    href: http://www.facebook.com/alina.mikhailova
  -
    ico: twitter.png
    href: http://twitter.com/ItsAlaMix
  -
    ico: myspace.png
    href: http://www.myspace.com/alya.mikhailova
  -
    ico: mail.png
    href: mailto:alya.mikhailova@gmail.com
  -
    ico: skype.png
    href: callto://alyamix
  -
    ico: icq.png
    href: http://www.icq.com/people/444882047
  -
    ico: youtube.png
    href: http://www.youtube.com/profile?user=AlaMix90
  -
    ico: picasa.png
    href: http://picasaweb.google.com/Alya.Mikhailova
content:
  'Портфоліо':
    color: 2
    text: >
      А тут будет информация, картинки, и все такое.<br />
      Пример:<br />
      <a href="http://wp-themes.com/minimalist/?TB_iframe=true&amp;width=600&amp;height=400" target="_blank">http://wp-themes.com/minimalist/?TB_iframe=true&amp;width=600&amp;height=400</a><br /><br />
      <img src="img/example_portfolio.jpg" alt="Пример картинки" />
  'Історія в обличчях':
    color: 1
    text: >
      Добавишь сама все, что хочешь!<br />
      А тут будет информация, картинки, и все такое.<br />
      Пример:<br />
      <a href="http://wp-themes.com/minimalist/?TB_iframe=true&amp;width=600&amp;height=400" target="_blank">http://wp-themes.com/minimalist/?TB_iframe=true&amp;width=600&amp;height=400</a><br /><br />
      <img src="img/example_portfolio.jpg" alt="Пример картинки" />
  'Блоги':
    color: 3
    text: >
      Не забывай меня просить о помощи :)<br />
      А тут будет информация, картинки, и все такое.<br />
      Пример:<br />
      <a href="http://wp-themes.com/minimalist/?TB_iframe=true&amp;width=600&amp;height=400" target="_blank">http://wp-themes.com/minimalist/?TB_iframe=true&amp;width=600&amp;height=400</a><br /><br />
      <img src="img/example_portfolio.jpg" alt="Пример картинки" />
  'Друзі сайту':
    color: 4
    text: >
      А тут будет информация, картинки, и все такое.<br />
      Пример:<br />
      <a href="http://wp-themes.com/minimalist/?TB_iframe=true&amp;width=600&amp;height=400" target="_blank">http://wp-themes.com/minimalist/?TB_iframe=true&amp;width=600&amp;height=400</a><br /><br />
      <img src="img/example_portfolio.jpg" alt="Пример картинки" />
  'Контакти':
    color: 0
    text: >
      А тут будет информация, картинки, и все такое.<br />
      Пример:<br />
      <a href="http://wp-themes.com/minimalist/?TB_iframe=true&amp;width=600&amp;height=400" target="_blank">http://wp-themes.com/minimalist/?TB_iframe=true&amp;width=600&amp;height=400</a><br /><br />
      <img src="img/example_portfolio.jpg" alt="Пример картинки" />