title: This is main page
content:
  -
    url: '#news_post_main'
    category: 0
    title: Що було і про що не написалось
    date: 12 грудня'10
    text: >
      Так багато хотілось написати: і про повернення Аньки додому (і
      постійні переїзди Київ-Скадовськ), про неймовірну жесть під
      назвою картинг, після якої кілька тижнів сходили синці, а Клайд
      обігнав канадців, отримав перше місце... <--->
  -
    squares: [1,2,3]
    url: '#media_post_main'
    category: 1
    title: The Big Bang Theory s04e04
    date: 16 жовтня'10
    text: >
      <iframe title="YouTube video player" width="320" height="195" src="http://www.youtube.com/embed/Xhcj7BK-XB4" style="border:none"></iframe>
  -
    squares: [1,3,4]
    url: '#photo_url_main'
    category: 2
    title: Марго и морожка
    date: 6 червня'10
    text: >
      Судак/ Сурож/ Сугдея/ Солдая/ Сидагиос курортный, если
      верить многочисленным рассказам, великолепен в месяцах
      июне и сентябре. Увы, упали карты так, что всунулись в жизнь
      этого города мы в самый пик: жары... <--->
      <br />
      <br />
      <a href="<-@->"><img src="img/example_margo.jpg" alt="Марго" /></a>
menu:
  -
    color: 2
    title: фото
    items:
      - ['Настенко', '#photo_Nastenko']
      - ['Марго', '#photo_Margo']
      - ['Чита', '#photo_Chita']
      - ['Рита', '#photo_Rita']
      - ['Дрита', '#photo_Drita']
  -
    color: 1
    title: медіа
    items:
      - ['Чита', '#media_Chita']
      - ['Рита', '#media_Rita']
      - ['Дрита', '#media_Drita']
  -
    color: 4
    title: AlaMix
    items:
      - ['Настенко', '#alamix_Nastenko']
      - ['Марго', '#alamix_Margo']
      - ['Дрита', '#alamix_Drita']
photo:
  text: випадкове фото
  color: 2
  url: '#random_photo'
  img: 'example_random.jpg'
  alt: