videos:
  -
    color: 2
    title: OTH
    items:
      - ['Серия 1', '#video_seriya1']
      - ['Серия 2', '#video_seriya2']
      - ['Серия 3', '#video_seriya3']
      - ['Серия 4', '#video_seriya4']
      - ['Серия 5', '#video_seriya5']
  -
    color: 1
    title: Gossip Girl
    items:
      - ['Серия 1', '#video_seriya1']
      - ['Серия 2', '#video_seriya2']
      - ['Серия 3', '#video_seriya3']
  -
    color: 4
    title: Big Bang Theory
    items:
      - ['Серия 1', '#video_seriya1']
      - ['Серия 2', '#video_seriya2']
      - ['Серия 3', '#video_seriya3']
  -
    color: 0
    title: Something else
    items:
      - ['Серия 1', '#video_seriya1']
music:
  - ['Aloha From Hell', '#aloha_from_hell']
  - ['Barenaked ladies', '#barenaked_ladies']
  - ['Blondie', '#blondie']
  - ['Bloodhoung Gang', '#bloodhoung_gang']
  - ['Cold', '#cold']
  - ['Coldplay', '#coldplay']
  - ['Dashboard Confessional', '#dashboard_confessional']
  - ['Blondie', '#blondie']
  - ['Bloodhoung Gang', '#bloodhoung_gang']
  - ['Barenaked ladies', '#barenaked_ladies']
  - ['Blondie', '#blondie']
  - ['Cold', '#cold']
  - ['Coldplay', '#coldplay']
  - ['Dashboard Confessional', '#dashboard_confessional']
  - ['Blondie', '#blondie']
  - ['Bloodhoung Gang', '#bloodhoung_gang']
  - ['Cold', '#cold']
  - ['Coldplay', '#coldplay']
  - ['Dashboard Confessional', '#dashboard_confessional']
  - ['Blondie', '#blondie']
  - ['Bloodhoung Gang', '#bloodhoung_gang']
  - ['Barenaked ladies', '#barenaked_ladies']
  - ['Blondie', '#blondie']
library:
  - ['Что-то из библиотеки', '#some_from_library1']
  - ['Какая-то ссылка', '#some_from_library2']
  - ['Библиотечный текст', '#some_from_library3']
  - ['Ссылка на что-то', '#some_from_library4']
  - ['Что-то еще', '#some_from_library5']
  - ['А тут я не придумал', '#some_from_library6']
  - ['Надо еще хотя бы пару линков', '#some_from_library7']
  - ['Очередной линк библиотеки', '#some_from_library8']
  - ['Предпоследний линк', '#some_from_library9']
  - ['Последний линк', '#some_from_library10']