videos:
  -
    color: 2
    items:
      - ['Season 1', 'http://al-mix.org.ua/mix/303']
      - ['Season 2', 'http://al-mix.org.ua/mix/310']
      - ['Season 3', 'http://al-mix.org.ua/mix/313']
      - ['Season 4', 'http://al-mix.org.ua/mix/316']
      - ['Season 5', 'http://al-mix.org.ua/mix/318']
      - ['Season 6', 'http://al-mix.org.ua/mix/323']
      - ['Season 7', 'http://al-mix.org.ua/mix/327']
      - ['Season 8', 'http://al-mix.org.ua/mix/329']
      - ['Season 9', 'http://al-mix.org.ua/mix/377']
  -
    color: 1
    items:
      - ['Season 1', 'http://al-mix.org.ua/mix/500/#gossip_girl_1']
      - ['Season 2', 'http://al-mix.org.ua/mix/500/#gossip_girl_2']
      - ['Season 3', 'http://al-mix.org.ua/mix/500/#gossip_girl_3']
      - ['Season 4', 'http://al-mix.org.ua/mix/500/#gossip_girl_4']
      - ['Season 5', 'http://al-mix.org.ua/mix/500/#gossip_girl_5']
  -
    color: 4
    items:
      - ['Season 1', 'http://al-mix.org.ua/mix/510/#The_Big_Bang_Theory_1']
      - ['Season 2', 'http://al-mix.org.ua/mix/510/#The_Big_Bang_Theory_2']
      - ['Season 3', 'http://al-mix.org.ua/mix/510/#The_Big_Bang_Theory_3']
      - ['Season 4', 'http://al-mix.org.ua/mix/510/#The_Big_Bang_Theory_4']
      - ['Season 5', 'http://al-mix.org.ua/mix/510/#The_Big_Bang_Theory_5']
  -
    color: 0
    items:
      - ['Season 1', 'http://al-mix.org.ua/mix/425#house_season_1']
      - ['Season 2', 'http://al-mix.org.ua/mix/425#house_season_2']
      - ['Season 3', 'http://al-mix.org.ua/mix/425#house_season_3']
      - ['Season 4', 'http://al-mix.org.ua/mix/425#house_season_4']
      - ['Season 5', 'http://al-mix.org.ua/mix/425#house_season_5']
      - ['Season 6', 'http://al-mix.org.ua/mix/425#house_season_6']
      - ['Season 7', 'http://al-mix.org.ua/mix/425#house_season_7']
      - ['Season 8', 'http://al-mix.org.ua/mix/425#house_season_8']
  -
    color: 4
    items:
      - ['Season 1', 'http://al-mix.org.ua/mix/515']
  -
    color: 0
    items:
      - ['Season 1', 'http://al-mix.org.ua/mix/522']
      - ['Season 2', 'http://al-mix.org.ua/mix/526']
  -
    color: 3
    items:
      - ['Season 1', 'http://al-mix.org.ua/mix/529']
  -
    color: 1
    items:
      - ['Season 1', 'link']
  -
    color: 1
    items:
      - ['Season 1', 'link']	  
music:
  - ['Wakey! Wakey!', 'http://al-mix.org.ua/mix/451']
library:
  - ['Д.Ліндсей “Дрімаючий Декстерів демон” ', 'http://al-mix.org.ua/mix/460']
