right_sidebar:
  -
    color: 2
    pretext: до теми
    content: <img src="../img/example_news_image1.jpg" alt="" />
    text: тут можно дописать всякие фигни, объясняющие, почему именно это изображение тут, и все такое
  -
    color: 1
    content: <embed type="application/x-shockwave-flash" flashvars="audioUrl=http://interscope.edgeboss.net/download/interscope/jimmyeatworld/invented/audio/my_best_theory.mp3" src="http://www.google.com/reader/ui/3523697345-audio-player.swf" width="400" height="27" quality="best"></embed>
    text: тут можно дописать всякие фигни, объясняющие, почему именно это аудио тут, и все такое.<br />Точно так же с оранжевым текстом под блоком видео
  -
    color: 4
    content: <img src="../img/example_news_image2.jpg" alt="" />
date_string: додано до розділу <a href="HOME" class="c0">Новини</a> %s
pagination:
  previous: '<span class="paginator-arrow">&#171;</span> давні дописи'
  next: 'новіші дописи <span class="paginator-arrow">&#187;</span>'