title: Mix Photos
photos:
  'Natural':
    -
      text: © Alina Mikhailova. Kyiv, Botanic Garden. 2009
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV8TBGU_rI/AAAAAAAAAZQ/mSIC7kx8egQ/s720/DSC_0696%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh5.googleusercontent.com/_2QfkN50ck4A/TXfqdYnIptI/AAAAAAAAAvQ/o2o9L7FIxzA/Natural_01.jpg
    -
      text: © Alina Mikhailova. Kyiv, Botanic Garden. 2009
      img: https://lh5.googleusercontent.com/_2QfkN50ck4A/TAV8T_nMjmI/AAAAAAAAAZY/mRZvj9U4850/s512/DSC_0699%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh6.googleusercontent.com/_2QfkN50ck4A/TXfqdb5ZjyI/AAAAAAAAAvM/O52jfcksomw/Natural_02.jpg
    -
      text: © Alina Mikhailova. Kyiv, Botanic Garden. 2009
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV8U8MRCpI/AAAAAAAAAZc/AdOkLWDWt5w/s512/DSC_0712%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh3.googleusercontent.com/_2QfkN50ck4A/TXfqdTXGf8I/AAAAAAAAAvI/pq-MRMc8bX8/Natural_03.jpg
    -
      text: © Alina Mikhailova. Kyiv, Botanic Garden. 2009
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV8WAyonwI/AAAAAAAAAZg/ll7dxI87kQg/s720/DSC_0713%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh6.googleusercontent.com/_2QfkN50ck4A/TXfqdiZ8gaI/AAAAAAAAAvU/K7x_ipp0Sdc/Natural_04.jpg
    -
      text: © Alina Mikhailova. Kyiv, Botanic Garden. 2009
      img: https://lh4.googleusercontent.com/_2QfkN50ck4A/TAV8XbnNeOI/AAAAAAAAAZk/yoC4uLGQhFU/s512/DSC_0757%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh6.googleusercontent.com/_2QfkN50ck4A/TXfqd9v3liI/AAAAAAAAAvY/4ceP4kboibo/Natural_05.jpg
    -
      text: © Alina Mikhailova. Kyiv, Botanic Garden. 2009
      img: https://lh3.googleusercontent.com/_2QfkN50ck4A/TAV8ZEzVBGI/AAAAAAAAAZs/5ncbUksr-G8/s720/DSC_0792%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh3.googleusercontent.com/_2QfkN50ck4A/TXfqd1pM53I/AAAAAAAAAvc/OFJd7s7YU14/Natural_06.jpg
    -
      text: © Alina Mikhailova. Kyiv, Botanic Garden. 2009
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV8aTqDQGI/AAAAAAAAAZw/gaL1fJLIRoQ/s720/DSC_0795%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh4.googleusercontent.com/_2QfkN50ck4A/TXfqeGIUIgI/AAAAAAAAAvg/UFWfSzCv4xg/Natural_07.jpg
  'Sunrise':
    -
      text: © Alina Mikhailova. Kyiv, Singing Field. 2009
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV8OrJCeqI/AAAAAAAAAY8/frBgjw1hbv0/s720/DSC_06842%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh6.googleusercontent.com/_2QfkN50ck4A/TXfuvFcKOuI/AAAAAAAAAvs/uwFEzfioWvE/Natural_08.jpg
    -
      text: © Alina Mikhailova. Kyiv, Singing Field. 2009
      img: https://lh4.googleusercontent.com/_2QfkN50ck4A/TAV8PsVgnFI/AAAAAAAAAZA/bsFI2UDmkFY/s720/DSC_0687%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh6.googleusercontent.com/_2QfkN50ck4A/TXfuvHZedCI/AAAAAAAAAvo/lC4PVco3z8c/Natural_09.jpg
    -
      text: © Alina Mikhailova. Kyiv, Singing Field. 2009
      img: https://lh3.googleusercontent.com/_2QfkN50ck4A/TAV8QkoTW3I/AAAAAAAAAZE/IHbdfwVtFnU/s720/DSC_0689%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh4.googleusercontent.com/_2QfkN50ck4A/TXfuvCgo54I/AAAAAAAAAv0/gsKoUrMwG5k/Natural_10.jpg
    -
      text: Ajuntament 01 © studio.es by Vincent Boiteau
      img: https://lh5.googleusercontent.com/_2QfkN50ck4A/TAV8RWh6j6I/AAAAAAAAAZI/eiiDIoBHwIo/s512/DSC_0701%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh5.googleusercontent.com/_2QfkN50ck4A/TXfuvYr0KSI/AAAAAAAAAvw/nZN52SMaitA/Natural_11.jpg