title: Mix Photos
photos:
  'Sunrise':
    -
      text: © Alina Mikhailova, 2009. Model: Rita Vershinina. Place: Kyiv, Singing Field. 
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV8OrJCeqI/AAAAAAAAAY8/frBgjw1hbv0/s720/DSC_06842%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh6.googleusercontent.com/_2QfkN50ck4A/TXfuvFcKOuI/AAAAAAAAAvs/uwFEzfioWvE/Natural_08.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Rita Vershinina. Place: Kyiv, Singing Field. 
      img: https://lh4.googleusercontent.com/_2QfkN50ck4A/TAV8PsVgnFI/AAAAAAAAAZA/bsFI2UDmkFY/s720/DSC_0687%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh6.googleusercontent.com/_2QfkN50ck4A/TXfuvHZedCI/AAAAAAAAAvo/lC4PVco3z8c/Natural_09.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Rita Vershinina. Place: Kyiv, Singing Field. 
      img: https://lh3.googleusercontent.com/_2QfkN50ck4A/TAV8QkoTW3I/AAAAAAAAAZE/IHbdfwVtFnU/s720/DSC_0689%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh4.googleusercontent.com/_2QfkN50ck4A/TXfuvCgo54I/AAAAAAAAAv0/gsKoUrMwG5k/Natural_10.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Rita Vershinina. Place: Kyiv, Singing Field. 
      img: https://lh5.googleusercontent.com/_2QfkN50ck4A/TAV8RWh6j6I/AAAAAAAAAZI/eiiDIoBHwIo/s512/DSC_0701%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh5.googleusercontent.com/_2QfkN50ck4A/TXfuvYr0KSI/AAAAAAAAAvw/nZN52SMaitA/Natural_11.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Nastenko Nastya. Place: Kyiv, Park Mariinskyi
      img: https://lh5.googleusercontent.com/_2QfkN50ck4A/TAV8J5T8V4I/AAAAAAAAAYk/gL9ugSJO6k4/s720/DSC_1649%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh5.googleusercontent.com/_2QfkN50ck4A/TXh5iDxgHzI/AAAAAAAAAwA/ziZ5-mzhqXQ/Natural_12.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Nastenko Nastya. Place: Kyiv, Park Mariinskyi
      img: https://lh5.googleusercontent.com/_2QfkN50ck4A/TAV8MBy7QOI/AAAAAAAAAYw/LZXp8yD4CDQ/s512/DSC_1658%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh4.googleusercontent.com/_2QfkN50ck4A/TXh6MUgeXWI/AAAAAAAAAwE/7wDE1ikjE5k/Natural_13.jpg
      'Stereotypes':
    -
      text: © Alina Mikhailova, 2009. Models: Nastya Samoshina, Nastya Nastenko. Place: Kyiv, institute of journalism
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV7VSbbA7I/AAAAAAAAAUs/e_fuG2-YUnw/s800/CSC_0341%20copy%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh6.googleusercontent.com/_2QfkN50ck4A/TXiD9aqEkgI/AAAAAAAAAwI/wIN3gqwTJIU/Stereotypes_01.jpg
    -
      text: Models: © Alina Mikhailova, 2009. Model: Tamara Tretyak. Place: Kyiv, institute of journalism
      img: https://lh3.googleusercontent.com/_2QfkN50ck4A/TAV7WoSjYaI/AAAAAAAAAU0/R9HYgSP4TzA/s512/CSC_0346%20copy%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh4.googleusercontent.com/_2QfkN50ck4A/TXiD9ZyWX6I/AAAAAAAAAwM/hpvxZU1K4P0/Stereotypes_02.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Nastya Nastenko. Place: Kyiv, institute of journalism
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV7XgSKq3I/AAAAAAAAAU4/yDsKi3YzUCU/s720/CSC_0353%20copy%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh3.googleusercontent.com/_2QfkN50ck4A/TXiD9XqhwpI/AAAAAAAAAwU/vzGI3s3PSZA/Stereotypes_03.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Nastya Nastenko. Place: Kyiv, Tymoshenko St.
      img: https://lh5.googleusercontent.com/_2QfkN50ck4A/TAV7YgONEGI/AAAAAAAAAU8/WRgQ3HgaS1c/s720/DSC_0469%20copy%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh3.googleusercontent.com/_2QfkN50ck4A/TXiD9grEI5I/AAAAAAAAAwQ/hAQILrm3Hoc/Stereotypes_04.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Nastya Nastenko. Place: Kyiv, Tymoshenko St.
      img: https://lh4.googleusercontent.com/_2QfkN50ck4A/TAV7ZSdNrWI/AAAAAAAAAVE/ntXa1CpuLdc/s720/DSC_0487%20copy%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh3.googleusercontent.com/_2QfkN50ck4A/TXiD92gTCMI/AAAAAAAAAwY/OrttgMwOcrk/Stereotypes_05.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Nastya Nastenko. Place: Kyiv, Tymoshenko St.
      img: https://lh3.googleusercontent.com/_2QfkN50ck4A/TAV7aUYQ3_I/AAAAAAAAAVI/j89YZ5GGlrg/s720/DSC_0489%20copy%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh3.googleusercontent.com/_2QfkN50ck4A/TXiD-G5yp8I/AAAAAAAAAwc/Yuy7n9Z9c0Y/Stereotypes_06.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Nastya Nastenko. Place: Kyiv, Tymoshenko St.
      img: https://lh5.googleusercontent.com/_2QfkN50ck4A/TAV7eqHRiQI/AAAAAAAAAVc/3GS0jmTkbno/s720/DSC_0622%20copy%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh6.googleusercontent.com/_2QfkN50ck4A/TXiD-NflzuI/AAAAAAAAAwg/KUpyiWsoBes/Stereotypes_07.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Nastya Nastenko. Place: Kyiv, Tymoshenko St.
      img: https://lh3.googleusercontent.com/_2QfkN50ck4A/TAV7fJdBtlI/AAAAAAAAAVg/sZvXoikrZHY/s512/DSC_0637%20copy%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh4.googleusercontent.com/_2QfkN50ck4A/TXiD-WESCSI/AAAAAAAAAwk/3OWDJo7fEB0/Stereotypes_08.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Nastya Nastenko. Place: Kyiv, Tymoshenko St.
      img: https://lh4.googleusercontent.com/_2QfkN50ck4A/TAV7ftTErmI/AAAAAAAAAVk/4NwmAmtQwOc/s512/DSC_0639%20copy%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh5.googleusercontent.com/_2QfkN50ck4A/TXiD-WT38LI/AAAAAAAAAws/eqYMweQlNSQ/Stereotypes_09.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Nastya Nastenko. Place: Kyiv, Tymoshenko St.
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV7gvmWnRI/AAAAAAAAAVo/jeXDaszgYqY/s720/DSC_0641%20copy%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh5.googleusercontent.com/_2QfkN50ck4A/TXiD-WT38LI/AAAAAAAAAws/eqYMweQlNSQ/Stereotypes_09.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Nastya Nastenko. Place: Kyiv, Tymoshenko St.
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV7hvt6xxI/AAAAAAAAAVs/wSVNEI9Vcqg/s720/DSC_0676%20copy%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh5.googleusercontent.com/_2QfkN50ck4A/TXiD-zRFNYI/AAAAAAAAAw0/yitpe1zz2gQ/Stereotypes_11.jpg
    -
      text: © Alina Mikhailova, 2009. Models: Sergey Akulinin, Nastya Nastenko. Place: Kyiv, Tymoshenko St.
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV7iW0jbEI/AAAAAAAAAV0/-SzGCDDgqgA/s512/DSC_0694%20copy%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh5.googleusercontent.com/_2QfkN50ck4A/TXiD-_wJ2CI/AAAAAAAAAww/Z0IJ6h3vojg/Stereotypes_12.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Nastya Nastenko. Place: Kyiv, Tymoshenko St.
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV7kQt3IHI/AAAAAAAAAV8/2qeAXttaQ9Y/s720/CSC_0709%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh5.googleusercontent.com/_2QfkN50ck4A/TXiD_KzMLFI/AAAAAAAAAw4/1BRddl99Xx8/Stereotypes_13.jpg
    -
      text: © Alina Mikhailova, 2009. Models: Sergey Akulinin, Nastya Nastenko. Place: Kyiv, Tymoshenko St.
      img: https://lh3.googleusercontent.com/_2QfkN50ck4A/TAV7lXqYnHI/AAAAAAAAAWA/6MGS0KWD3CI/s720/DSC_0727%20copy%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh3.googleusercontent.com/_2QfkN50ck4A/TXiD_ahhftI/AAAAAAAAAxA/7rpY5tXb2P8/Stereotypes_14.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Nastya Nastenko. Place: Kyiv, Tymoshenko St.
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV7mVeLVXI/AAAAAAAAAWE/T8bb3pQIphY/s720/CSC_0746%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh6.googleusercontent.com/_2QfkN50ck4A/TXiD_d0A3gI/AAAAAAAAAw8/9T2z2AIpvoc/Stereotypes_15.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Nastya Nastenko. Place: Kyiv, Tymoshenko St.
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV7n3RhQFI/AAAAAAAAAWM/kgUtckEfb1A/s512/CSC_0762%20copy%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh3.googleusercontent.com/_2QfkN50ck4A/TXiD_mxsqgI/AAAAAAAAAxE/mAkM_3PASJo/Stereotypes_16.jpg
    -
      text: © Alina Mikhailova, 2009. Model: Nastya Nastenko. Place: Kyiv, Tymoshenko St.
      img: https://lh5.googleusercontent.com/_2QfkN50ck4A/TAV7qqspjLI/AAAAAAAAAWc/0rrZMLYv5lg/s720/DSC_0781%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh6.googleusercontent.com/_2QfkN50ck4A/TXiD_4CiEXI/AAAAAAAAAxI/M-juokSGpiA/Stereotypes_17.jpg
    - 
      text: © Alina Mikhailova, 2009. Model: Nastya Nastenko. Place: Kyiv, Tymoshenko St.
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV7r6INVRI/AAAAAAAAAWg/Oy4xACLOfS4/s720/DSC_0785%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh6.googleusercontent.com/_2QfkN50ck4A/TXiD_-Del-I/AAAAAAAAAxQ/El0VTpg1ZjQ/Stereotypes_18.jpg
    - 
      text: © Alina Mikhailova, 2009. Model: Nastya Nastenko. Place: Kyiv, Tymoshenko St.
      img: https://lh4.googleusercontent.com/_2QfkN50ck4A/TAV7soG4ctI/AAAAAAAAAWk/UtxYxd4ZT14/s720/DSC_0787%20copy%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh6.googleusercontent.com/_2QfkN50ck4A/TXiD_56Wy1I/AAAAAAAAAxM/R7WvXJUxp90/Stereotypes_19.jpg
    - 
      text: © Alina Mikhailova, 2009. Model: Nastya Nastenko. Place: Kyiv, Tymoshenko St.
      img: https://lh4.googleusercontent.com/_2QfkN50ck4A/TAV7tgX4aPI/AAAAAAAAAWo/FxjQIyNyRXI/s720/CSC_0801%20copy%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh4.googleusercontent.com/_2QfkN50ck4A/TXiEAaQmtaI/AAAAAAAAAxU/8XU30cKPIUw/Stereotypes_20.jpg
  'Natural':
    -
      text: © Alina Mikhailova. Kyiv, Botanic Garden. 2009
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV8TBGU_rI/AAAAAAAAAZQ/mSIC7kx8egQ/s720/DSC_0696%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh5.googleusercontent.com/_2QfkN50ck4A/TXfqdYnIptI/AAAAAAAAAvQ/o2o9L7FIxzA/Natural_01.jpg
    -
      text: © Alina Mikhailova. Kyiv, Botanic Garden. 2009
      img: https://lh5.googleusercontent.com/_2QfkN50ck4A/TAV8T_nMjmI/AAAAAAAAAZY/mRZvj9U4850/s512/DSC_0699%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh6.googleusercontent.com/_2QfkN50ck4A/TXfqdb5ZjyI/AAAAAAAAAvM/O52jfcksomw/Natural_02.jpg
    -
      text: © Alina Mikhailova. Kyiv, Botanic Garden. 2009
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV8WAyonwI/AAAAAAAAAZg/ll7dxI87kQg/s720/DSC_0713%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh6.googleusercontent.com/_2QfkN50ck4A/TXfqdiZ8gaI/AAAAAAAAAvU/K7x_ipp0Sdc/Natural_04.jpg
    -
      text: © Alina Mikhailova. Kyiv, Botanic Garden. 2009
      img: https://lh4.googleusercontent.com/_2QfkN50ck4A/TAV8XbnNeOI/AAAAAAAAAZk/yoC4uLGQhFU/s512/DSC_0757%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh6.googleusercontent.com/_2QfkN50ck4A/TXfqd9v3liI/AAAAAAAAAvY/4ceP4kboibo/Natural_05.jpg
    -
      text: © Alina Mikhailova. Kyiv, Botanic Garden. 2009
      img: https://lh3.googleusercontent.com/_2QfkN50ck4A/TAV8ZEzVBGI/AAAAAAAAAZs/5ncbUksr-G8/s720/DSC_0792%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh3.googleusercontent.com/_2QfkN50ck4A/TXfqd1pM53I/AAAAAAAAAvc/OFJd7s7YU14/Natural_06.jpg
    -
      text: © Alina Mikhailova. Kyiv, Botanic Garden. 2009
      img: https://lh6.googleusercontent.com/_2QfkN50ck4A/TAV8aTqDQGI/AAAAAAAAAZw/gaL1fJLIRoQ/s720/DSC_0795%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg
      thumb: https://lh4.googleusercontent.com/_2QfkN50ck4A/TXfqeGIUIgI/AAAAAAAAAvg/UFWfSzCv4xg/Natural_07.jpg