title: Портфоліо page
content:
  -
    title: Назва
    description: небольшое описание
    color: 0
    items:
      - '<div style="background-color:#e97749;width:420px;height:266px"></div>'
      - '<div style="background-color:#0f0f0f"><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" style="width:420px;height:266px" id="b1149e9a-6fae-7b61-a291-51df58129ffe" ><param name="movie" value="http://static.issuu.com/webembed/viewers/style1/v2/IssuuReader.swf?mode=mini&amp;shareMenuEnabled=false&amp;printButtonEnabled=false&amp;shareButtonEnabled=false&amp;searchButtonEnabled=false&amp;backgroundColor=%23222222&amp;documentId=111106191213-deacdd934c8246cf85a6e1d4bcd3e573" /><param name="allowfullscreen" value="true"/><param name="menu" value="false"/><param name="wmode" value="transparent"/><embed src="http://static.issuu.com/webembed/viewers/style1/v2/IssuuReader.swf" type="application/x-shockwave-flash" allowfullscreen="true" menu="false" wmode="transparent" style="width:420px;height:266px" flashvars="mode=mini&amp;shareMenuEnabled=false&amp;printButtonEnabled=false&amp;shareButtonEnabled=false&amp;searchButtonEnabled=false&amp;backgroundColor=%23222222&amp;documentId=111106191213-deacdd934c8246cf85a6e1d4bcd3e573" /></object></div>'
      - '<div style="background-color:#88c02b;width:420px;height:266px"></div>'
      - '<div style="background-color:#06caff;width:420px;height:266px"></div>'
  -
    title: Назва 2
    description: небольшое описание 2
    color: 1
    items:
      - '<div style="background-color:#c37077;width:420px;height:266px"></div>'
      - '<div style="background-color:#e97749;width:420px;height:266px"></div>'
      - '<div style="background-color:#88c02b;width:420px;height:266px"></div>'
  -
    title: Назва 3
    description: небольшое описание 3
    color: 2
    items:
      - '<div style="background-color:#06caff;width:420px;height:266px"></div>'
      - '<div style="background-color:#dd2150;width:420px;height:266px"></div>'
      - '<div style="background-color:#e97749;width:420px;height:266px"></div>'
  -
    title: Назва 4
    description: небольшое описание 4
    color: 4
    items:
      - '<div style="background-color:#88c02b;width:420px;height:266px"></div>'
      - '<div style="background-color:#06caff;width:420px;height:266px"></div>'
      - '<div style="background-color:#c37077;width:420px;height:266px"></div>'
