search_text: пошук
search_button: Пошук
not_found: не знайдено жодного допису
continue_reading: <span class="meta-nav">&darr;</span> Більше
edit_post_link:
  - Редагувати
  - <span class="edit-link">
  - '</span> <span class="meta-sep">|</span>&#160;'
comments:
  - Без коментарів
  - 1 коментар
  - % коментарів
post_comments:
  passw_protection: Цей допис закритий паролем. Введіть пароль, щоб побачити коментарі.
  title:
    - 'Одна відгук на &#171;%2$s&#187;'
    - '%1$s відгуків на &#171;%2$s&#187;'
  pagination:
    previous: '<span class="paginator-arrow">&#171;</span> Попередні коментарі'
    next: 'Наступні коментарі <span class="paginator-arrow">&#187;</span>'
  closed: Коментарі закриті
  comment_form:
    must_log_in: Ви маєте <a href="%s">увійти</a> щоб залишити свій коментар.
    logged_in_as: Ви війшли як <a href="%1$s">%2$s</a>. <a href="%3$s" title="Вийти з цього аккаунту">Вийти?</a>
    comment_notes_before: Ваша email адреса не буде опублікована.
    comment_notes_after: Ви можете використовувати наступні <abbr title="HyperText Markup Language">HTML</abbr> теги та атрибути: %s
    title_reply: Залишити відповідь
    title_reply_to: Залишити відповідь на %s
    cancel_reply_link: Відмінити відповідь
    label_submit: Залишити відгук
archive:
  title:
    day:
      text: Добовий архів: <span>%s</span>
      format: ''
    month:
      text: Архів за %s
      format: F, Y
    year:
      text: Річний архів: <span>%s</span>
      format: Y
    common: Архів новин
search: 'Результати пошуку &#171;%s&#187;:'