search_text: пошук
search_button: Пошук
not_found: не знайдено жодного допису
continue_reading: <span class="meta-nav">&darr;</span> Більше
edit_post_link:
  - Редагувати
  - <span class="edit-link">
  - '</span> <span class="meta-sep">|</span>&#160;'
comments:
  - Без коментарів
  - 1 коментар
  - % коментарів