search_text: пошук
search_button: Пошук
not_found: не знайдено жодного допису
continue_reading: <span class="meta-nav">&darr;</span> Більше
edit_post_link:
  - Редагувати
  - <span class="edit-link">
  - '</span> <span class="meta-sep">|</span>&#160;'
comments:
  - Без коментарів
  - 1 коментар
  - % коментарів
post_comments:
  passw_protection: This post is password protected. Enter the password to view any comments.
  title:
    - 'Одна відповідь на &#171;%2$s&#187;'
    - '%1$s відповіді на &#171;%2$s&#187;'
  pagination:
    previous: '<span class="paginator-arrow">&#171;</span> Попередні коментарі'
    next: 'Наступні коментарі <span class="paginator-arrow">&#187;</span>'
archive:
  title:
    day:
      text: Добовий архів: <span>%s</span>
      format: ''
    month:
      text: Архів за %s
      format: F, Y
    year:
      text: Річний архів: <span>%s</span>
      format: Y
    common: Архів новин
search: 'Результати пошуку &#171;%s&#187;:'